#!/usr/bin/env bash

killall -q polybar

if type "xrandr"
then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1)
	do
		MONITOR=$m polybar polybar_nic 2>&1 | tee -a /tmp/polybar.log & disown
	done
else
	polybar polybar_nic 2>&1 | tee -a /tmp/polybar.log & disown
fi
